using ECommerce.Application.DTOs;
using ECommerce.Application.Interfaces;
using ECommerce.Domain.Entities;

namespace ECommerce.Application.Services;

public class ProductService : IProductService
{
    private readonly IProductRepository _productRepository;
    private readonly ICacheService _cacheService;

    private const string AllProductsCacheKey = "products:all";

    public ProductService(
        IProductRepository productRepository,
        ICacheService cacheService)
    {
        _productRepository = productRepository;
        _cacheService = cacheService;
    }

    // =========================================================
    // GET ALL PRODUCTS
    // =========================================================

    public async Task<IEnumerable<ProductDto>> GetAllAsync()
    {
        var cachedProducts =
            await _cacheService.GetAsync<List<ProductDto>>(
                AllProductsCacheKey);

        if (cachedProducts != null)
        {
            return cachedProducts;
        }

        var products =
            await _productRepository.GetAllAsync();

        var productDtos =
            products.Select(MapToDto).ToList();

        await _cacheService.SetAsync(
            AllProductsCacheKey,
            productDtos,
            TimeSpan.FromMinutes(5));

        return productDtos;
    }

    // =========================================================
    // GET PRODUCT BY ID
    // =========================================================

    public async Task<ProductDto?> GetByIdAsync(int id)
    {
        var cacheKey = $"product:{id}";

        var cachedProduct =
            await _cacheService.GetAsync<ProductDto>(cacheKey);

        if (cachedProduct != null)
        {
            return cachedProduct;
        }

        var product =
            await _productRepository.GetByIdAsync(id);

        if (product == null)
        {
            return null;
        }

        var productDto = MapToDto(product);

        await _cacheService.SetAsync(
            cacheKey,
            productDto,
            TimeSpan.FromMinutes(5));

        return productDto;
    }

    // =========================================================
    // CREATE PRODUCT - ADMIN
    // =========================================================

    public async Task<ProductDto> CreateAsync(
        CreateProductDto dto)
    {
        if (string.IsNullOrWhiteSpace(dto.Name))
        {
            throw new ArgumentException(
                "Product name is required.");
        }

        if (dto.Price < 0)
        {
            throw new ArgumentException(
                "Product price cannot be negative.");
        }

        if (dto.StockQuantity < 0)
        {
            throw new ArgumentException(
                "Stock quantity cannot be negative.");
        }

        var product = new Product
        {
            Name = dto.Name.Trim(),
            Description = dto.Description?.Trim() ?? string.Empty,
            Price = dto.Price,
            StockQuantity = dto.StockQuantity,
            CategoryId = dto.CategoryId
        };

        await _productRepository.AddAsync(product);

        // Product ID is generated by the database.
        // SaveChanges is handled by the repository.
        await _productRepository.UpdateAsync(product);

        // Product catalog has changed.
        await _cacheService.RemoveAsync(AllProductsCacheKey);

        return MapToDto(product);
    }

    // =========================================================
    // UPDATE PRODUCT - ADMIN
    // =========================================================

    public async Task<ProductDto?> UpdateAsync(
        int id,
        UpdateProductDto dto)
    {
        if (string.IsNullOrWhiteSpace(dto.Name))
        {
            throw new ArgumentException(
                "Product name is required.");
        }

        if (dto.Price < 0)
        {
            throw new ArgumentException(
                "Product price cannot be negative.");
        }

        if (dto.StockQuantity < 0)
        {
            throw new ArgumentException(
                "Stock quantity cannot be negative.");
        }

        var product =
            await _productRepository.GetByIdAsync(id);

        if (product == null)
        {
            return null;
        }

        product.Name = dto.Name.Trim();
        product.Description =
            dto.Description?.Trim() ?? string.Empty;
        product.Price = dto.Price;
        product.StockQuantity = dto.StockQuantity;
        product.CategoryId = dto.CategoryId;

        await _productRepository.UpdateAsync(product);

        await _cacheService.RemoveAsync(
            $"product:{id}");

        await _cacheService.RemoveAsync(
            AllProductsCacheKey);

        return MapToDto(product);
    }

    // =========================================================
    // DELETE PRODUCT - ADMIN
    // =========================================================

    public async Task<bool> DeleteAsync(int id)
    {
        var product =
            await _productRepository.GetByIdAsync(id);

        if (product == null)
        {
            return false;
        }

        await _productRepository.DeleteAsync(id);

        await _cacheService.RemoveAsync(
            $"product:{id}");

        await _cacheService.RemoveAsync(
            AllProductsCacheKey);

        return true;
    }

    // =========================================================
    // MAPPING
    // =========================================================

    private static ProductDto MapToDto(Product product)
    {
        return new ProductDto
        {
            Id = product.Id,
            Name = product.Name,
            Description = product.Description,
            Price = product.Price,
            StockQuantity = product.StockQuantity,
            CategoryId = product.CategoryId
        };
    }
}